name: ishadow-updater
 
on:
  push:
  schedule:
    - cron: '20 */6 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      # 设置 python 版本
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # 安装 python 依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests AdvancedHTMLParser
      # 执行仓库中的脚本文件
      - name: run update
        run: python -u ./ishadow-util.py
      - name: push
        run: |
          pwd
          ls -l
          git config --global user.email "hengchen2005@gmial.com"
          git config --global user.name "yushuibo"
          git add -A
          git commit -m "github action auto updated"
          git push origin main
